eng/sdk_files/Emscripten.Node.props
eng/sdk_files/Emscripten.Python.props

Simplified Preview4 fix for https://github.com/dotnet/runtime/issues/51535 in release/6.0-preview4 where the tooling paths were not setup correctly
Normal Blazor AOT build in preview4 will fail to find the packaged tooling
Tested locally
Very low, AOT build related only tooling fix

[release/6.0-preview4] Set tooling paths correctly

---

eng/sdk_files/Emscripten.Node.props
eng/sdk_files/Emscripten.Python.props
eng/sdk_files/Emscripten.Sdk.props

Instead of depending on `WasmApp.targets` to set the `PATH` using the correct properties, add them directory to `@(EmscriptenPrependPath)`, which will get added to `PATH`.

[wasm] Add the paths to binaries, to `@(EmscriptenPrependPath)`

---

eng/sdk_files/Emscripten.Python.props

We add the path containing the python binaries from the packages to
`PATH`, but that contains `python3`, and not `python`. When we run
`emcc --version` on a machine without a system python, it fails with
`unable to find python in $PATH`
This was not caught with our regular testing, possibly because a system
`python` was available on those machines.
`emsdk_env.sh` sets `EMSDK_PYTHON = /Users/radical/dev/r3/src/mono/wasm/emsdk/python/3.7.4-2_64bit/bin/python3`
.. so, this commit adds the same for running `emcc`, and sets that to
`python3` from the package.
This was tested on macOS.

Set `EMSDK_PYTHON=../python3` to match what `emsdk_env.sh` does

---

eng/sdk_files/Emscripten.Python.props

(cherry picked from commit 80b4baa20e3c0c33a6d17dae28cdec6ccf39e0ee)

[backport release/6.0-preview5] Set `EMSDK_PYTHON=../python3` to match what `emsdk_env.sh` does (#19)

---

eng/sdk_files/Emscripten.Python.props

Backport a fix for correctly locating installed python to Preview5.
Without this fix Wasm AOT will fail on macos systems without python in PATH
Tested manually after discovering while writing e2e tests for workload installation.
Very low.
(cherry picked from commit 80b4baa20e3c0c33a6d17dae28cdec6ccf39e0ee)
Earlier backport landed in the wrong branch.

[backport release/6.0-preview5] Set EMSDK_PYTHON correctly

---

eng/emsdk.proj

we need to test the workloads in use before upgrading too.
On windows, `emcc` ends up invoking `"C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0-preview.7.21323.1\tools\bin\clang++.exe"`, but that file is missing on the sdk package.
And that manifests as:
```
WasmApp.Native.targets(268,5): error : Failed to compile C:\dev\bl1\obj\Debug\net6.0\wasm\System.Private.Uri.dll.bc -> C:\dev\bl1\obj\Debug\net6.0\wasm\System.Private.Uri.dll.o: C:\dev\bl1>setlocal [C:\dev\bl1\bl1.csproj]
WasmApp.Native.targets(268,5): error : C:\dev\bl1>set errorlevel=dummy  [C:\dev\bl1\bl1.csproj]
WasmApp.Native.targets(268,5): error : C:\dev\bl1>set errorlevel=  [C:\dev\bl1\bl1.csproj]
WasmApp.Native.targets(268,5): error : C:\dev\bl1>emcc …
```

Recent releases use clang++

---

eng/sdk_files/Emscripten.Python.props

Python defaults to the system charset, and thus expects the files it's reading to
match that. But that might not always be true. Eg. system charset=gbk, failing to read
utf-8 files.
See https://github.com/dotnet/runtime/issues/53367 for the motivating issue
Moving this here, from runtime's `WasmApp.Native.targets`.

Set `PYTHONUTF8=1` for python pack

---

eng/.emscripten

This would allow this to be overridden when we are trying to use local per-project caches.

Allow `FROZEN_CACHE` to be overridden by user projects

---

eng/emsdk.proj

Delete these libs on windows, where we are over the nuget size limit.
Context: https://github.com/dotnet/emsdk/pull/34#issuecomment-872691739
That should affect build times when using
[debug sanitizers](https://emscripten.org/docs/debugging/Sanitizers.html)
which is not used by default builds.
Also remove `mt` libs. We don't support threads yet anyway.

Delete selected libs from cache to shrink size

---

eng/Build.props
eng/Publishing.props
eng/Versions.props
eng/azure-pipelines.yml
eng/emsdk.proj
eng/workloads/Directory.Build.props
eng/workloads/VSSetup.props
eng/workloads/VSSetup.targets
eng/workloads/emsdk.vsmanproj
eng/workloads/workloads.csproj

Backport of https://github.com/dotnet/emsdk/pull/45 to release/6.0-preview7.
Without this PR, customers will not be able to install EMSDK workloads into Visual Studio
We validated the packages produced are satisfactory to be inserted into VS.
Very low.

[release/6.0-preview7] Build VS installers for EMSDK workloads

---

eng/Publishing.props

Temporary fix for the blob path issues for the wixpacks. Previously the missing _UploadPathRoot was causing paths like:
`/wixpack//foofile.6.0.0-preview.1234.wixpack.zip`
This causes problems in gather drop due to Path.Combine behavior (the rooted path wins and the file is placed in the root of the directory structure).
This is not a full solution, because when stable builds happen, these paths must be unique. At that point, the `foofile.6.0.0-preview.1234.wixpack.zip` will end up foofile.6.0.0.wixpack.zip, which
will be non-unique in blob storage.
Fixing this requires a bit of messing about to get full version info in the publishing targets, so deferring that for now and unblocking signing.

[release/6.0-preview7] Fixup blob paths interim

---

eng/nuget/Microsoft.NET.Workload.Emscripten.Manifest/WorkloadManifest.targets

Needed to support https://github.com/dotnet/runtime/pull/56606 .

Disable workload for projects targeting <net6.0

---

eng/workloads/workloads.csproj

backport of https://github.com/dotnet/emsdk/pull/87
* Tweak workload build to use _GenerateMsiVersionString target
Replaces GenerateVersions that wasn't quite accurate enough for what we need
* Import wix targets directly
* Copy in the arcade task - will remmove later
* More tweaks
* Make sure things happen in build target
* Forgot a depends target
Co-authored-by: Steve Pfister <steve.pfister@microsoft.com>

[release/6.0] Tweak workload build to use _GenerateMsiVersionString target

---

eng/emsdk.proj

These 2 tools were added with the emscripten 2.0.34 and increase the nuget
size a lot.
+  70,630,912 tools/bin/clang-repl.exe *2
+   8,182,272 tools/bin/llvm-ml.exe *2
They are not present in the emscripten 3.1.1, so I think it should be
fine to remove them.

Remove unused tools on windows

---

eng/Versions.props

To allow rollback of emscripten in dotnet/runtime 7.0-preview2 branch

[release/7.0-preview2] Go back to emscripten 2.0.23

---

eng/Versions.props

https://github.com/dotnet/emsdk/pull/111 bumped to 6.0.3. To avoid confusion, align with what runtime is on now (6.0.4)

Bump VersionPrefix to 6.0.4

---

eng/nuget/Microsoft.NET.Workload.Emscripten.Manifest/WorkloadManifest.json.in

Reverts dotnet/emsdk#109
Rolling this back because it appears to be racy in the workload processing step with the same assets

Revert "Add emulated win-arm64 packs"

---

eng/Publishing.props
eng/Signing.props
eng/azure-pipelines.yml
eng/common-variables.yml

- Add an explicit flag for post-build signing
- In-build signing is only supported on Windows. This repo creates some packages on Mac and Linux, and at the moment they can only be created on those platforms. When post build signing isn't enabled, download the artifacts for those platforms and run the sign and publish phases of the build.
- Update the cert for the MSIs to be the .NET Cert
- Move the PostBuildSIgn flag into the YAML so it can be used in template expressions
- Pass -sign (harmless if post-build sign is on) in all ci cases.
- Always publish even on PRs, there's no harm in it.

Add support for in-build signing

---

eng/common-variables.yml

In the PR https://github.com/dotnet/emsdk/pull/164 a new variable was added conditionally:
```yml
- ${{ if eq(variables['PostBuildSign'], 'true') }}:
- name: _NonWindowsInternalPublishArg
value: -publish
```
.. but this resulted in the variable not getting defined at all in the final yaml.
We need to move the if to the variable _value_ instead.
FYI @mmitche

Fix publishing for non-windows platforms

---

eng/Version.Details.xml
eng/Versions.props
eng/common/cross/build-rootfs.sh
eng/common/generate-locproject.ps1
eng/common/sdk-task.ps1
eng/common/tools.ps1
eng/workloads/workloads.csproj
global.json

* Update arcade to 7.0.0-beta.22416.1
* Workload changes
Co-authored-by: Larry Ewing <lewing@microsoft.com>

[release/7.0-rc1] Workload changes and arcade update (#171)

---

eng/Versions.props

These packages are in dotnet-public is there any reason not to reference them while we sort this out?

[release/7.0-rc1] Rollback 6.0.x

---

eng/Versions.props

Reverts dotnet/emsdk#177
Once there is a package in dotnet7 feed with the 6.0,8 reference we should revert the rollback.

Revert "[release/7.0-rc1] Rollback 6.0.x"

---

eng/Versions.props

mea culpa on not checking the feeds for 6.0.8, I forgot we hadn't really published those packages even internally
because I would really like to see a runtime build working with these packages I think it is worth landing this for another build cycle, the alternative is pushing 6.0.8 packs to a feed runtime can use.

[release/7.0-rc1] make a 6.0.4 build

---

eng/Versions.props

Reverts dotnet/emsdk#180 once the build is published.

Revert "[release/7.0-rc1] make a 6.0.4 build"

---

eng/Signing.props

.cat files cannot be dual signed. However, there was a bug in signtool.exe where an attempt to add a second signature did not fail, and instead corrupted the cat file. Validation steps were added in the signing process to avoid this situation, and this broke builds.

[release/7.0-rc1] Do not attempt to sign .cat files

---

eng/Signing.props

Set the python.cat signature to None so that tooling doesn't complain about not having a signature mapping for this file.

Explicitly avoid signing python.cat

---

eng/Signing.props

commit 5ef661392ae7b1595b683df83d63e3a0365fc126
Author: Matt Mitchell <mmitche@microsoft.com>
Date:   Wed Aug 24 09:22:40 2022 -0700
Explicitly avoid signing python.cat (#192)
Set the python.cat signature to None so that tooling doesn't complain about not having a signature mapping for this file.
commit 321399ab3ab4853fbf861b2eaed2113447a6d7e4
Author: Matt Mitchell <mmitche@microsoft.com>
Date:   Tue Aug 23 11:51:37 2022 -0700
Do not attempt to sign .cat files (#190)
.cat files cannot be dual signed. However, there was a bug in signtool.exe where an attempt to add a second signature did not fail, and instead corrupted the cat file. Validation steps were added in the signing process to avoid this situation, and this broke builds.

[release/7.0] sync rc1

---

eng/Versions.props

staging this for october, if it needs to go in sooner remove the version bump

[release/6.0] Stop publishing 6.0.200 sdk band and bump release version

---

eng/Signing.props

.cat files cannot be dual signed. However, there was a bug in signtool.exe where an attempt to add a second signature did not fail, and instead corrupted the cat file. Validation steps were added in the signing process to avoid this situation, and this broke builds.
Also fix the msi signing cert to be .NET's

Do not attempt to sign .cat files (#190)

---

eng/emsdk.proj
eng/nuget/Microsoft.NET.Runtime.Emscripten.Cache/Microsoft.NET.Runtime.Emscripten.Cache.pkgproj
eng/nuget/Microsoft.NET.Runtime.Emscripten.Cache/Microsoft.NET.Runtime.Emscripten.Cache.props
eng/nuget/Microsoft.NET.Workload.Emscripten.net7.Manifest/WorkloadManifest.json.in
eng/nuget/Microsoft.NET.Workload.Emscripten.net7.Manifest/WorkloadManifest.targets
eng/sdk_files/Emscripten.Cache.props
eng/sdk_files/Emscripten.Cache.targets

This is a forward port of #208 to `main`
---
Spin out the emscripten system libraries cache into a separate nupkg.
- Split up the Emscripten SDK by moving the system libraries cache into a separate nupkg.
- make a new Emscripten Cache SDK that includes just the cache directory
- the Cache SDK overrides the WasmCachePath (if it's not set by the user) to point into the Cache SDK
we leave the mt multithreaded libraries in the cache. (But we remove the ww WebWorker (non-pthread) Emscripten API libraries)
Addresses dotnet/runtime#75263

[main] [wasm-mt] Create a Microsoft.NET.Runtime.Emscripten.Cache

---

eng/Version.Details.xml
eng/Versions.props
eng/workloads/workloads.csproj
global.json

Update Arcade and port changes from 6.0 to split workloads artifacts into separate zips for packs and components/manifests for VS insertions

Split workloads into packs/components

---

eng/Versions.props

Automatically calculate the net6 patch version based on the net7 patch version. This is to prevent any instance where we forget to bump it manually.

[release/7.0][workloads] Automatically calculate the net6 patch version

---

eng/emsdk.proj

Building with `/p:ForceBuildManifestOnly=true` skips the emsdk build, but emits manifest nupkgs (and msi on windows)

Add property to build manifests only and skip EMSDK build itself

---

eng/SourceBuild.props

Yes, this indicates managed artifacts only. For now, we are only attempting to source-build the emsdk manifest, not the full packages, so the statement is true.
Needed to add emsdk to source-build/VMR, and prevent:
```  
/home/directhex/Projects/dotnet/src/emsdk/artifacts/obj/ArcadeGeneratedProjects/SourceBuildIntermediate/SourceBuildIntermediate.proj(43,5): error : GitHubRepositoryName property is not defined.
```

Add a baseline SourceBuild.props

---

eng/workloads/workloads.csproj

Fix net6 workload component versions. net7 version of https://github.com/dotnet/emsdk/pull/279

[release/7.0] Set versions for net6

---

.gitignore
eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/Microsoft.NET.Workload.Emscripten.Current.Manifest.pkgproj

Use .Transport instead of _Transport in unversioned manifest name

---

eng/SourceBuild.props

Fixes: https://github.com/dotnet/source-build/issues/3336
The issue was introduced by https://github.com/dotnet/emsdk/pull/312, which isn't currently needed in this repo. As a result none of the projects were built in source-build which introduced 3 prebuilts.

Disable TFM trimming

---

README.md
bazel/emscripten_deps.bzl
bazel/emscripten_toolchain/toolchain.bzl
bazel/revisions.bzl
emscripten-releases-tags.json
emsdk.py
emsdk_manifest.json
eng/Versions.props
eng/clang-wrapper.sh
eng/common/native/init-compiler.sh
eng/emsdk.proj
test/test.py

This reverts commit 750b3ac11c6170fb6795f5cf276c240a73ffc8e1.

Bump emscripten to 3.1.34

---

Directory.Build.props
eng/SourceBuild.props

Fixes: https://github.com/dotnet/source-build/issues/3417
This is a backport of the patch, implemented in `installer` with https://github.com/dotnet/installer/pull/16214
`NoTargetFrameworkFiltering` property, in `emsdk` repo, should be moved from `eng/SourceBuild.props` to `Directory.Build.props`. 
This would match the implementation in the `runtime` repo (https://github.com/dotnet/runtime/blob/018a9bd43851c998f9239aedf2fcc09c5eff7488/Directory.Build.props#L304-L305).

Move NoTargetFrameworkFiltering property

---

eng/Versions.props

The previous version was set to 7.0.6 and it does not exist.

Bump downlevel version to 7.0.7

---

eng/Versions.props

7.0.6 is not a real version, so this corrects it.

[release/8.0-preview5] Bump downlevel version to 7.0.7

---

eng/Versions.props

Reverts dotnet/emsdk#349 I'm going to roll this back so main can still test downlevel

Revert "Bump downlevel version to 7.0.7"

---

eng/Versions.props

previous pr accidentally went back to 7.0.6 which also doesn't exist

Roll back to 7.0.5 which is public

---

eng/Publishing.props

Saves about 500MB of artifacts.

Do not publish wixpacks when postbuild sign is not true

---

eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/WorkloadManifest.targets

Similar to how Blazor SDK supports building app without workload, WebAssembly SDK should too.

Allow WebAssembly SDK without workload

---

eng/azure-pipelines.yml
eng/emsdk.proj

Relying on a different AssetManfiest in the workloads build, so putting x64 back in.

[release/8.0-preview7] Add back in x64 build

---

eng/Version.Details.xml

We should coherency tie runtime's llvm-project to emsdk to avoid incoherency that may cause build drop size issues. Add dependencies for coherency

Add dependencies for coherency

---

eng/sdk_files/Emscripten.Sdk.props

Fixes https://github.com/dotnet/runtime/issues/61306

Add properties `$(EmscriptenVersion)`, and `$(EmscriptenRevision)`

---

eng/Version.Details.xml

These were in the toolset section in runtime, but likely all llvm versions should be aligned there.

Add more dependencies for coherency

---

eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/WorkloadManifest.targets
eng/nuget/Microsoft.NET.Workload.Emscripten.net7.Manifest/WorkloadManifest.targets

- Fix condition for `UsingBrowserRuntimeWorkload` value ("AOT or not (wasm sdk or blazor sdk)")
- Fixing change from https://github.com/dotnet/emsdk/pull/381
- Remove duplicated logic from .NET 7 targets ("sync" .NET 6 and 7 manifest)

Fix WebAssembly SDK without workload

---

eng/Versions.props
eng/workloads/workloads.csproj

Manifest installers for .NET optional workloads rely on performing major upgrades in .NET 6 and 7. This requires that the MSI version increments for new builds. The MSI version was generated using the assembly file version. MSI versions should be generated using the major/minor/patch/buildnumber, e.g. 6.0.20.12345. Because the assembly file version was being used, the version will eventually get wrapped due to the bit masking and shift operations used to construct the MSI version. MSI [ProductVersion](https://learn.microsoft.com/en-us/windows/win32/msi/productversion) is only 32-bits in size (8-bit major, 8-bit minor and 16-bit build number).
For 6.0.21, the ProductVersion generated using the old method was 48.35.64643 and for 6.0.22 it generated 48.32.658.
1. Visual Studio PR checks fail …

[release/6.0] emscripten: Fix workload manifest MSI ProductVersion generation

---

eng/workloads/workloads.csproj

Manifest installers for .NET optional workloads rely on performing major upgrades in .NET 6 and 7. This requires that the MSI version increments for new builds. The MSI version was generated using the assembly file version. MSI versions should be generated using the major/minor/patch/buildnumber, e.g. 7.0.10.12345. Because the assembly file version was being used, the version will eventually get wrapped due to the bit masking and shift operations used to construct the MSI version. MSI [ProductVersion](https://learn.microsoft.com/en-us/windows/win32/msi/productversion) is only 32-bits in size (8-bit major, 8-bit minor and 16-bit build number).
For 7.0.10, the ProductVersion generated using the old method was 56.35.64642 and for 7.0.11 it generated 56.32.531
Visual Studio PR checks fail …

[release/7.0] emscripten: Fix workload manifest MSI ProductVersion generation

---

eng/Versions.props
eng/workloads/workloads.csproj

This is a port of the recent version fixes for manifest installers.
See the following for the 6/7 changes.
https://github.com/dotnet/emsdk/pull/441
https://github.com/dotnet/emsdk/pull/440
We need this before 8.0 ships so we are consistent across the board.

Fix manifest MSI version generation

---

eng/nuget/Microsoft.NET.Runtime.Emscripten.Common.props

This issue was found during the .NET 8 Test build. Fixes https://dev.azure.com/dnceng/internal/_build/results?buildId=2260881&view=results

Check DotNetFinalVersionKind when setting WorkloadVersionSuffix

---

eng/emsdk_env.sh
eng/nuget/Microsoft.NET.Runtime.Emscripten.Sdk/Microsoft.NET.Runtime.Emscripten.Sdk.props

Would you believe this change is sufficient to enable building ICU with our emsdk (when paired with a lot of env vars)?
I was originally going to ship the upstream emsdk_env.sh, but that carries a LOT of dependencies on other files from the emsdk repo, and also the `construct_env` command doesn't work properly unless the directory layout is very specific, which is a problem for us. Instead, a simple script to add our env vars (which we already use in wasm publishing) to $PATH in the same manner, bypassing the need for emsdk.py entirely.

Add home-made emsdk_env.sh

---

eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/Microsoft.NET.Workload.Emscripten.Current.Manifest.pkgproj

Microsoft.NET.Workload.Emscripten.Current.Manifest is a non shipping package and shouldn't have a stable version

Dont stabilize non shipping package

---

eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/Microsoft.NET.Workload.Emscripten.Current.Manifest.pkgproj

Microsoft.NET.Workload.Emscripten.Current.Manifest is a non shipping package and shouldn't have a stable version

Don't stabilize non shipping package

---

eng/nuget/Microsoft.NET.Workload.Emscripten.net8.Manifest/WorkloadManifest.targets

Fixes:
`/root/helix/work/workitem/e/dotnet-latest/sdk-manifests/9.0.100-alpha.1/microsoft.net.workload.emscripten.net8/WorkloadManifest.targets(4,5): warning MSB4011: "/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Node.linux-x64/9.0.0-alpha.1.23469.6/Sdk/Sdk.props" cannot be imported again. It was already imported at "/root/helix/work/workitem/e/dotnet-latest/sdk-manifests/9.0.100-alpha.1/microsoft.net.workload.emscripten.current/WorkloadManifest.targets (23,5)". This is most likely a build authoring error. This subsequent import will be ignored. `

net8/WorkloadManifest.targets: import only for tfm=net8.0, and not tfm>=net8.0

---

eng/emsdk.proj
eng/sanitize.py

Currently, the emscripten version is hardcoded to 8.0.0. This won't work when we move to 8.0.1 (https://dev.azure.com/dnceng/internal/_build/results?buildId=2273068&view=results) This should fix the issue

[release/8.0] Pass emscripten path as argument to Sanitize.py

---

eng/emsdk.proj
eng/sanitize.py

Currently, the emscripten version is hardcoded to GA version. This won't work when we move to servicing (https://dev.azure.com/dnceng/internal/_build/results?buildId=2273068&view=results) This should fix the issue

Pass emscripten path as argument to Sanitize.py

---

eng/clang-wrapper.sh

Fixes https://github.com/dotnet/runtime/issues/92335.

Fix clang-wrapper.sh so it handles arguments with spaces.

---

eng/sdk_files/Emscripten.Cache.props
eng/sdk_files/Emscripten.Cache.targets

This removes the dependence on a target to set this.

Emscripten.Cache.*: Set WasmCachePath in Sdk.props instead of in a target

---

eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/WorkloadManifest.json.in

Should be the missing fix for https://github.com/dotnet/sdk/issues/32327 though likely these changes need to flow though to updated runtime (and maybe SDK) builds.

Add missing workload references to Musl native EMSDK

---

eng/Publishing.props

Backport of https://github.com/dotnet/emsdk/pull/685 to release/6.0

[release/6.0] Set ProducesDotNetReleaseShippingAssets property in Publishing.props

---

eng/emsdk_env.cmd
eng/nuget/Microsoft.NET.Runtime.Emscripten.Sdk/Microsoft.NET.Runtime.Emscripten.Sdk.props

The batch script does exactly the same thing as the sh version (sets needed env variables). This is needed if we are to use the transport packages to build runtime.

Add emsdk_env.cmd to set up the environment for the Emscripten SDK on windows

---

eng/azure-pipelines.yml
eng/common-variables.yml

All the artifacts are present, so we only need to sign once

Only sign and publish once at the join point

---

eng/Version.Details.xml

No longer produced by the llvm build.

Remove ObjWriter packages

---

eng/Version.Details.xml

No longer produced by the llvm build.

[release/9.0-preview3] Remove ObjWriter packages

---

eng/workloads/workloads.csproj

To automate VSDROP insertions from staging builds, we need to include some additional metadata that is difficult to obtain from staging builds, like the assembly file version that is used when versioning drop components. 
Manually verified metadata against internal builds. Cannot be fully tested until we have a fully staged build and all the automation pipelines completed.

Add metadata for workload automation

---

eng/Versions.props

this can be fast merged if we're taking it, I think we need it to insert into vs, no of the tests test downlevel

[release/9.0-preview4] Bump downlevel versions to 8.0.5

---

eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/WorkloadManifest.targets.in

- Include emscripten workload also if `UsingEmscriptenWorkload=true`
- Allows to use emscripten workload for NativeAOT-LLVM without browser workload

Allow to use emscripten workload separately

---

eng/Versions.props

Port of https://github.com/dotnet/emsdk/pull/842 to main.
Only merge this once 8.0.8 is stable.

Bump downlevel versions to 8.0.8

---

eng/SignCheckExclusionsFile.txt
eng/Signing.props
eng/azure-pipelines.yml
eng/emsdk.proj

The goal here is to sign everything we can.  After much testing the main insight is that 3PartyScriptsSHA2 works for the script files and some of the previously complicated files no longer exist.  There are still a couple of problems:
1.  It is actively wrong to sign the emscripten library js since emscripten uses text transforms to combine it all together so we should test what ends up in the output before merging this.  Because  of this it's likely we'll need to not sign js still.  I don't see a workable way to sign some tooling js and not the library js (perhaps we could sign some files before they are packaged?)
2.  The arcade tooling shouldn't attempt to sign zero length files, it will fail and retry until timeout. There are valid reasons for thing like zero length `__init__.py` …

Sign almost all the things

---

eng/azure-pipelines-public.yml
eng/azure-pipelines.yml

We can do this now that the dnceng-provided images contain the 1ES prerequisites.

Use same AzDO images in the official build as we do in public

---

Directory.Build.props

emsdk.py started reading files out of the tool directories but in servicing we aren't bumping the version in emsdk_manifest.json so they weren't found.
Don't include the patch version in the tool directories to fix this.

Fix versioned directories for tools in Directory.Build.props

---

eng/Versions.props
eng/nuget/Microsoft.NET.Runtime.Emscripten.Common.props

see discussion at https://github.com/dotnet/sdk/pull/43554

[release/9.0] Treat rtm as stable workload band

---

eng/Versions.props
eng/nuget/Microsoft.NET.Runtime.Emscripten.Common.props

Backport of the hotfix in release/9.0

[workloads] Consider rtm a stable workload band

---

eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/WorkloadManifest.targets.in

The `TreatPreviousAsCurrent` is currently empty, but we don't want to treat current as 9.
The possible way to ensure `TreatPreviousAsCurrent` is set before emscripten is imported is to move the property initialization to `AutoImport.props` which always imports before WorkloadManifest.targets

Fix TreatPreviousAsCurrent check

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/emsdk.proj

Fixes https://github.com/dotnet/source-build/issues/5014
We can do this for emsdk already since emsdk doesn't build in source-build anymore.

Remove source-build related code

---

eng/azure-pipelines-public.yml
eng/azure-pipelines.yml

The Unix legs shouldn't use cibuild.sh as that unconditionally passes the sign and publish switch in.
Also pass the `prepareMachine` flag in.
Set /p:Test=false when using the CIBuild.cmd script for official builds.

Fix official build script invocations

---

eng/emsdk_env.cmd
eng/emsdk_env.sh

We were prepending the full path to python.exe to PATH instead of just the directory. This caused us to not actually use our own python, but fallback to a system-installed one, since PATH works with directories.
https://github.com/dotnet/emsdk/pull/735 most likely hit the same issue but since there's no system-installed node this failed and we instead added an _additional_ variable for the node directory.
This is unnecessary, we can just grab the directory from the .exe.
Also fixed the comment that made it sound like we're _appending_ to PATH, we're actually prepending.

Fix prepending python directory to PATH
