- eng/azure-pipelines.yml
Useful to look at the packages without waiting for the internal build to finish and push to feeds.
> Upload nuget packages to AzDO

- eng/Signing.props
cc: @trevors20 @akoeplinger @mmitche
> Disable signing unsupported files

- eng/Version.Details.xml
- eng/Versions.props
- eng/workloads/workloads.csproj
A couple of dependencies were not added to Version.Details.xml, leading to them not being updated.
> [release/6.0-preview7] Add missing dependencies to Version.Details.xml

- eng/Publishing.props
See discussion on https://github.com/dotnet/runtime/issues/57154
> Publish assets in requested folder layout to BAR

- eng/Signing.props
- eng/Version.Details.xml
- eng/Versions.props
Port https://github.com/dotnet/emsdk/pull/68 to the main branch.
Also apply a suggestion to add dependencies into Version.Details.xml from #45
> [main] Include .msi files in post build signing

- eng/Versions.props
- eng/workloads/workloads.csproj
Part of https://github.com/dotnet/runtime/issues/59498
> [release/6.0-rc2] Use the dual signed wix package

- eng/Versions.props
- eng/workloads/workloads.csproj
Packaging update to fix emsdk side of https://github.com/dotnet/runtime/issues/60003
> [release/6.0] Signed wix redux

- eng/Versions.props
To avoid darc picking up the latest packages with 3.1.1
> Go back to emscripten 2.0.23

- eng/Versions.props
Makes sure we're generating the latest sdk band manifest.
> Generate 300 band emsdk manifest

- eng/clang-wrapper.sh
- eng/emsdk.proj
- eng/sanitize.py
Get the packages under the nuget.org size limit and more aggressively clean devDependencies until all the fixes are upstreamed.
> Fix package versions

- eng/nuget/Microsoft.NET.Runtime.Emscripten.Common.props
This is already fixed in main.
> fix typo in url

- eng/Versions.props
> Roll emsdk install forward to 3.1.12 (again)

- eng/Version.Details.xml
- eng/Versions.props
- eng/common/cross/build-rootfs.sh
- eng/common/generate-locproject.ps1
- eng/common/sdk-task.ps1
- eng/common/tools.ps1
- eng/workloads/workloads.csproj
- global.json
- Update arcade to 7.0.0-beta.22416.1
- Workload changes
cc: @joeloff
> Workload changes and arcade update

- eng/Publishing.props
- eng/Signing.props
manual run with in post build signing = false at [Pipelines - Run 20220830.4 (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=1977145&view=results)
> [release/7.0] Publish and sign the VSDrop zip

- eng/Signing.props
- eng/Versions.props
- eng/workloads/workloads.csproj
> Backport workload packaging fixes

- eng/Versions.props
There is no rush here I just don't want to fall behind
> [release/7.0] Bump 6.0.x version

- eng/Versions.props
> Compute 6.0.x from 7.0.x

- eng/workloads/workloads.csproj
@joeloff  Is this what you mean or something else?
> include all the component workloads

- eng/SourceBuildPrebuiltBaseline.xml
- eng/Version.Details.xml
- eng/Versions.props
- eng/azure-pipelines.yml
- eng/emsdk.proj
There were version conflicts in the automated backport
> [release/8.0-preview1] Try enabling Source Build intermediate artifacts

- eng/workloads/workloads.csproj
> [release/7.0] fix the workload component reference.

- README.md
- bazel/emscripten_deps.bzl
- bazel/emscripten_toolchain/toolchain.bzl
- bazel/revisions.bzl
- emscripten-releases-tags.json
- emsdk.py
- emsdk_manifest.json
- eng/Versions.props
- eng/clang-wrapper.sh
- eng/common/native/init-compiler.sh
- eng/emsdk.proj
- test/test.py
> Revert "Bump emscripten to 3.1.34"

- eng/Versions.props
cc @marcpopMSFT @mmitche @steveisok
> Roll back the 7.0.x version for p4

- eng/azure-pipelines.yml
Build emsdk on arm64 and then emsdk and workloads on x64
> [release/8.0-preview7] Fix publishing

- eng/azure-pipelines.yml
- eng/emsdk.proj
Will prevent colliding packages
> [release/8.0-preview7] Prevent Building Emsdk.Internal on arm64

- eng/azure-pipelines.yml
- eng/emsdk.proj
This is so source build doesn't complain.
> [release/8.0-preview7] Put back windows only condition on Internal package

- eng/azure-pipelines.yml
- eng/emsdk.proj
After https://github.com/dotnet/emsdk/pull/386 and friends, bring changes to main to fix publishing.
> Fix publishing

- eng/Version.Details.xml
- eng/Versions.props
Backport of https://github.com/dotnet/emsdk/pull/389
> [release/8.0-preview7] Update llvm-project to match the one coming from binaryen

- eng/Signing.props
(cherry picked from commit 6b0c0592ee9781bc1c6a17d638e4878b9c1d5e21)
> [release/8.0-rc1] Change cert for .cat

- eng/Versions.props
We may need this depending on what ships in the next release
> [release/8.0] Avoid reving downlevel

- eng/Versions.props
> Revert "[release/8.0] Avoid reving downlevel"

- eng/Versions.props
This was missed in the branding updates, so updating.
> [release/6.0] Update Version.props

- eng/Versions.props
Counterpart to https://github.com/dotnet/runtime/pull/98853
> Update PackageVersionNet8 to 8.0.2

- eng/azure-pipelines.yml
- eng/common-variables.yml
* Only run publish at join point (#714)
(cherry picked from commit 1ed00a9ab199b9a20ad2e65b8164ed81aa7f4031)
* Only sign and publish once
* Set asset manifest file name
> Only sign and publish once at the join point (#717)

- eng/Versions.props
don't merge until 8.0.5 is released
> Bump the downlevel versions

- eng/Versions.props
update preview5 downlevel versions
> [release/9.0-preview5] Update Versions.props

- eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/Microsoft.NET.Workload.Emscripten.Current.Manifest.pkgproj
- eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/WorkloadManifest.json.in
- eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/WorkloadManifest.targets
> [workloads] Use stable names so they will match downlevel 

- eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/Microsoft.NET.Workload.Emscripten.Current.Manifest.pkgproj
- eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/WorkloadManifest.json.in
> [release/8.0][workload] use stable names for future versions

- eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/WorkloadManifest.targets.in
> [release/8.0] Add lost commit back

- eng/Versions.props
The branding document was incorrect.
> Switch to preview7 not rc1

- eng/azure-pipelines.yml
They were on the edge and sometime timeouted
> Increase windows build timeouts

- eng/Versions.props
this need to go into preview7 branch once it has been created
> [release/9.0-preview7] Bump downlevel versions to 8.0.8

- eng/Versions.props
- eng/emsdk.proj
- eng/nuget/Microsoft.NET.Workload.Emscripten.Current.Manifest/WorkloadManifest.targets.in
- eng/nuget/Microsoft.NET.Workload.Emscripten.net9.Manifest/Microsoft.NET.Workload.Emscripten.net9.Manifest.pkgproj
- eng/nuget/Microsoft.NET.Workload.Emscripten.net9.Manifest/WorkloadManifest.json.in
- eng/nuget/Microsoft.NET.Workload.Emscripten.net9.Manifest/WorkloadManifest.targets
Also fixes a small typo in the "current" manifest .targets
> Add net9 workload manifest

- eng/azure-pipelines-public.yml
- eng/azure-pipelines.yml
Remove the `enableSourceBuild` parameter from Azure Pipelines configuration files.
> Disable SourceBuild, it's not needed here anymore

- eng/Versions.props
Updates version branding in eng/Versions.props to rc1
> Update version branding to rc1
